# App name 
spring.application.name=java-mvc-productmanagement-sin-jpa

# =========================
# DATABASE (Render + Local)
# =========================

# Usa variables de entorno (con fallback para local)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_db01}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# SQL INIT
# =========================
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false

# =========================
# SERVER
# =========================
# Render usa PORT dinámico
server.port=${PORT:8080}